services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Treupo\CustomDashboardWidgets\:
    resource: '../Classes/*'

  Treupo\CustomDashboardWidgets\Widgets\Provider\PagesWithoutDescriptionDataProvider:
    arguments:
      $excludedDoktypes: [3, 4, 6, 7, 199, 254, 255]
      $limit: 8
